### ISSUE TITLE
Better scripts with ArgParse.jl

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/LESbrary.jl#10]
To make setting up simulations much easier. Some needed flags include
* resolution and extend flags
* `--output-dir`
* `--sose-dir`
* `--latitude`
* `--longitude`
* `--days`
* `--forcing=false/true` (turn off forcing for debugging)

**Comment by glwagner** [comment]
Should we also come up with a naming convention ?

**Comment by glwagner** [comment]
Would

* `start-date`
* `end-date`

make sense?

**Comment by ali-ramadhan** [comment]
Ah yeah `start-date` and `end-date` would be a good idea!

**Comment by ali-ramadhan** [comment]
We've been doing this, e.g. with `three_layer_constant_fluxes.jl`.
