### ISSUE TITLE
Manifest.toml should be ignored

### ISSUE THREAD

**Issue by sandreza** [CliMA/LESbrary.jl#135]
We should remove the Manifest.toml from the repository

**Comment by glwagner** [comment]
We have found it creates less work for us to keep it. But if it's a problem for you we can consider to compat maintainence instead.

**Comment by glwagner** [comment]
@navidcy

**Comment by navidcy** [comment]
> We should remove the Manifest.toml from the repository

Why you saying so? Did you notice something?

**Comment by sandreza** [comment]
Ah, I didn't realize it was done on purpose! We can close the issue then. (sorry for the noise)
