### ISSUE TITLE
Best way to support NetCDF output?

### ISSUE THREAD

**Issue by ali-ramadhan** [CliMA/LESbrary.jl#28]
Hoping to run https://github.com/CliMA/LESbrary.jl/blob/master/examples/three_layer_constant_fluxes.jl and output to NetCDF but wondering whether it's a good idea to add an `--output {jld2,netcdf}` flag to the script's command line arguments?

**Comment by glwagner** [comment]
Before doing that I think we need to bite the bullet and refactor `JLD2OutputWriter` so that we can have this option by writing

```julia
OutputWriter = Symbol(args["output"], :OutputWriter)
```

**Comment by ali-ramadhan** [comment]
Ah yes resolving https://github.com/CliMA/Oceananigans.jl/issues/884 would make this a trival change.

I might do NetCDF on a branch if I need it.

**Comment by ali-ramadhan** [comment]
On Zoom a few weeks ago, @glwagner, @adelinehillier, and I decided to output JLD2 and NetCDF since the file size for 1D statistics is small.
