### ISSUE TITLE
A bug in computing the shear production?

### ISSUE THREAD

**Issue by qingli411** [CliMA/LESbrary.jl#30]
https://github.com/CliMA/LESbrary.jl/blob/9a25401e2e689b000d0d3c27380fbec082f13e56/src/TurbulenceStatistics/shear_production.jl#L58

@glwagner  Should `U` in this line be `V` instead? Might contribute to the excessively strong shear production we saw in the Langmuir turbulence runs.

**Comment by glwagner** [comment]
That's for sure!
