### ISSUE TITLE
Remove Plots.jl dependencies when running simulations

### ISSUE THREAD

**Issue by xkykai** [CliMA/LESbrary.jl#66]
Error message when running `examples/three_layer_constant_fluxes` on Satori:
```
┌ Error: Error building `GR`:
│ tar (child): downloads/gr-0.53.0-Linux-powerpc64le.tar.gz: Cannot open: No such file or directory
│ tar (child): Error is not recoverable: exiting now
│ tar: Child returned status 2
│ tar: Error is not recoverable: exiting now
│ [ Info: Downloading pre-compiled GR 0.53.0 Linux binary
│ ┌ Error: Download failed: curl: (22) The requested URL returned error: 404 Not Found
│ └ @ Base download.jl:43
│ ┌ Error: Download failed: curl: (22) The requested URL returned error: 404 Not Found
│ └ @ Base download.jl:43
│ [ Info: Using insecure connection
│ ┌ Error: Download failed: curl: (22) The requested URL returned error: 404 Not Found
│ └ @ Base download.jl:43
│ [ Info: Cannot download GR run-time
│ ERROR: LoadError: failed process: Process(`tar xzf downloads/gr-0.53.0-Linux-powerpc64le.tar.gz`, ProcessExited(2)) [2]
```

Perhaps `Plots.jl` dependency can be removed from scripts running simulations to be able to run on Satori.

**Comment by ali-ramadhan** [comment]
Yeah might be good to also remove the PyPlot.jl dependency to avoid issues when building/instantiating on headless servers.

The scripts can still use Plots and PyPlot but then it would be up to us to install the plotting packages before running.

**Comment by ali-ramadhan** [comment]
In PR #108 CairoMakie.jl and Plots.jl are no longer direct dependencies (just test dependencies) so this shouldn't be an issue anymore.

Also, `three_layer_constant_fluxes.jl` uses CairoMakie.jl which works on Satori (at least it did last time I tried).
