### ISSUE TITLE
Mean buoyancy budget in 2Day suite simulations

### ISSUE THREAD

**Issue by sandreza** [CliMA/LESbrary.jl#70]
Plotting the mean buoyancy in time for some of the 2Day suite simulations seems to not satisfy the mean buoyancy budget.
In particular

```julia
using JLD2, Statistics, Plots
filename = pwd() * "/three_layer_constant_fluxes_hr48_Qu0.0e+00_Qb1.2e-07_f1.0e-04_Nh256_Nz128_free_convection_averaged_statistics.jld2"
file = jldopen(filename)

αg = 0.00196133

keys(file["timeseries"]["u"])
u = []
v = []
b = []
e = []
t = []
for key in keys(file["timeseries"]["u"])
    push!(u,file["timeseries"]["u"][key]*1.0)
    push!(v,file["timeseries"]["v"][key]*1.0)
    push!(b,file["timeseries"]["b"][key]*1.0)
    push!(e,file["timeseries"]["e"][key]*1.0)
    push!(t,file["timeseries"]["t"][key]*1.0)
end

plot(t, mean.(b))
```

yields a plot that isn't a straight line

**Comment by sandreza** [comment]
<img width="572" alt="Screen Shot 2021-01-10 at 11 48 35 PM" src="https://user-images.githubusercontent.com/22668662/104198892-68c41400-53ec-11eb-9a75-3bf0d6b2e9bd.png">

**Comment by sandreza** [comment]
Actually, this may be due to the fact that what I grabbed are the time-averaged statistics as opposed to the instantaneous. This would explain the factor of two discrepancies in the slope as compared to the expected budget, as well as initial transient

**Comment by sandreza** [comment]
That was indeed the case. Using statistics.nc (instead of averaged_statistcs.nc)

```julia
using NCDatasets, Statistics, Plots
files = [
    pwd() * "/three_layer_constant_fluxes_cubic_hr48_Qu0.0e+00_Qb1.0e-08_f1.0e-04_Nh256_Nz128_free_convection_2days_Qb1e-8.nc",
    pwd() * "/checkthis.nc"
]
file = files[2]
ds = Dataset(file,"r")
field = ds["T"]
t = ds["time"][:]
meanT = zeros(length(t))
key = keys(field)
for i in eachindex(t) 
    meanT[i] = mean(field[:,i])  
end

plot(t, meanT)

αg = 0.00196133
for  i in 2:length(t)
    println(αg * (meanT[i-1] - meanT[i]) / (t[i] - t[i-1]))
end
```
yielded 
<img width="571" alt="Screen Shot 2021-01-11 at 11 28 23 AM" src="https://user-images.githubusercontent.com/22668662/104210492-931bce80-53f8-11eb-8907-a97b86657f0b.png">

**Comment by glwagner** [comment]
Maybe we should use `time_averaged_statistics.nc` and `instantaneous_statistics.nc` as filenames?

**Comment by ali-ramadhan** [comment]
Yeah I'd be on board with these clearer names.

**Comment by sandreza** [comment]
Same here!

**Comment by ali-ramadhan** [comment]
These names are now in use on the master branch (switch was made in PR #56).
