### ISSUE TITLE
Use `time_averaged_statistics.nc` and `instantaneous_statistics.nc` as filenames for LESbrary output?

### ISSUE THREAD

**Issue by glwagner** [CliMA/LESbrary.jl#71]
Maybe we should use `time_averaged_statistics.nc` and `instantaneous_statistics.nc` as filenames?

_Originally posted by @glwagner in https://github.com/CliMA/LESbrary.jl/issues/70#issuecomment-758704439_

**Comment by ali-ramadhan** [comment]
These names are now in use on the master branch (switch was made in PR #56).
