### ISSUE TITLE
Can't install LESbrary.jl because of Oceananigans dependency

### ISSUE THREAD

**Issue by tomchor** [CliMA/LESbrary.jl#97]
```julia
julia> Pkg.add(url="https://github.com/CliMA/LESbrary.jl.git")
    Cloning git-repo `https://github.com/CliMA/LESbrary.jl.git`
   Updating git-repo `https://github.com/CliMA/LESbrary.jl.git`
   Updating registry at `~/.julia/registries/General`
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Oceananigans [9e8cae18]:
 Oceananigans [9e8cae18] log:
 ├─possible versions are: 0.53.0 or uninstalled
 ├─restricted to versions 0.47-0.48 by LESbrary [0d21a966] — no versions left
 │ └─LESbrary [0d21a966] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─LESbrary [0d21a966] is fixed to version 0.1.0
 └─Oceananigans [9e8cae18] is fixed to version 0.53.0
```

Oceananigans is changing versions extremely fast. Maybe it's worth changing the Oceananigans `[compat]` entry to something like "^0"? So that every version until `1.0` will in principle be supported?

**Comment by ali-ramadhan** [comment]
Yes, good catch. LESbrary.jl isn't a registered package so we can definitely get away with using a `"^0"` compat entry.

**Comment by ali-ramadhan** [comment]
I'll remove the `[compat]` entries on a different branch. Should probably also get rid of CompatHelper and TagBot until we want to register LESbrary.jl as a proper package. I'll also update LESbrary.jl to use the latest version of Oceananigans.jl

**Comment by tomchor** [comment]
> Should probably also get rid of CompatHelper and TagBot until we want to register LESbrary.jl as a proper package. 

So, why not register it as a proper package?

**Comment by tomchor** [comment]
> Ah so LESbrary.jl depends on Oceanostics.jl but I just noticed you already updated the compatibility there!

Yes! Although I am now realizing that I will probably need to release a new version there for this change to "take effect". I gotta figure out how to do that haha

**Comment by ali-ramadhan** [comment]
Ah found a place that could be used to tag a new version: https://github.com/tomchor/Oceanostics.jl/commit/8359a430a6e1ff088850d8a666a7cd32b33548a3

> So, why not register it as a proper package?

Hmmm, not sure. I guess LESbrary.jl still feels a little rough and has some heavy dependencies. I think we should resolve #66 and get rid of the Plots.jl and CairoMakie.jl dependencies before registering it as a new package. They're not even really used by LESbrary.jl, just by the "examples".
